<?php

require_once('includes/ringcentral-functions.inc');
require_once('includes/ringcentral-php-functions.inc');
require_once('includes/ringcentral-db-functions.inc');
require_once('includes/ringcentral-curl-functions.inc');

show_errors();

get_audit_data('U0pDMDFQMDlQQVMwMHxBQUIwcldqZVVJOVR1bXk5Nmg3YUctSkl1Z3pwZ0dEQ3RkSkxqdHA2QWxfVXYwdlA3YnpvbG12YmdQN3NKSlFkelZaZ3hIaDRkUjZybldjMlN5b1ZPOE1FMDl0NlZUT2JIOHotLWJIZTVGNnNSRUoweVI2RTRseG5DYjZEaGczc2htamZkeC1VSGZEcTBLbmdjSGpQOV9uYlZZMmozVmpDeGtYM0c5Zkp6bTdjSUhkSW5SWjQ5WnFwR0VvOVNpWE1XOUVrR0NmQUFkS3lfdFlUZHhWaGVrUmhjUGhjS2d8Wnl3aEh3fC1QZlpaRHBSQWVLeFBJc3ZGVmYwWnd8QVF8QUF8QUFBQUFGaVZqZTg');

